site_name: AppFriends Documentation
site_description: 'A turn-key solution to enable messagina and make your app social.'
site_author: 'Hao Wang'
site_url: 'http://www.appfriends.me'
site_favicon: images/logo.png

# Copyright
copyright: 'Copyright (c) 2016 Hacknocraft'

theme: 'material'
pages:
- Welcome: index.md
- iOS:
  - 'Quick Start': 'ios/quick_start.md'
  - 'Sessions': 'ios/sessions.md'
  - 'Users': 'ios/users.md'
  - 'Social': 'ios/social.md'
  - 'Dialogs and Messaging': 'ios/dialogs.md'
  - 'Push Notification': 'ios/push_notification.md'
  - 'Events': 'ios/events.md'
  - 'Encryption': 'ios/encryption.md'
  - 'UI Components': 'ios/ui_components.md'
  - 'UI Customization': 'ios/ui_customization.md'
  - 'External Dependencies': 'ios/dependencies.md'
  - 'Errors': 'ios/error.md'
- Android:
  - 'Quick Start': 'android/quick_start.md'
  - 'Sessions': 'android/sessions.md'
  - 'Users': 'android/users.md'
  - 'Social': 'android/social.md'
  - 'Dialogs and Messaging': 'android/dialogs.md'
  - 'Push Notifications Guide': 'android/push.md'
  - 'Encryption': 'android/encryption.md'
  - 'UI Integration Guide': 'android/ui.md'
  - 'UI Customization Guide': 'android/customization.md'
  - 'Errors & Exceptions': 'android/error.md'
- Javascript:
  - 'Quick Start': 'javascript/quick_start.md'
  - 'Callbacks & Events': 'javascript/events.md'
  - 'Users': 'javascript/users.md'
  - 'Dialogs': 'javascript/dialogs.md'
  - 'Messaging': 'javascript/messaging.md'
  - 'Social': 'javascript/social.md'
- Server API:
  - 'Request Authentication': 'api/request_auth.md'
  - 'Application APIs': 'api/applicationapi.md'
  - 'Admin APIs': 'api/adminapi.md'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)

extra_css:
    - css/extra.css

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'deep orange'
    accent: 'orange'
  font:
    text: 'Open Sans'
    code: 'Monaco'
  social:
    - type: 'github'
      link: 'https://github.com/Hacknocraft/'
