site_name: AppFriends Documentation
site_description: 'A turn-key solution to enable messagina and make your app social.'
site_author: 'Hao Wang'
site_url: 'http://www.appfriends.me'
site_favicon: images/logo.png

# Copyright
copyright: 'Copyright (c) 2016 Hacknocraft'

theme: 'material'
pages:
- Welcome: index.md
- iOS:
  - 'Quick Start': 'ios/quick_start.md'
  - 'Users': 'ios/users.md'
  - 'Chat': 'ios/chat.md'
  - 'UI Components': 'ios/ui_components.md'
  - 'External Dependencies': 'ios/dependencies.md'
- Android:
  - 'Quick Start': 'android/quick_start.md'
  - 'UI Customization': 'android/customization.md'
- Server API:
  - 'Request Authentication': 'api/request_auth.md'
  - 'Application APIs': 'api/applicationapi.md'
  - 'Admin APIs': 'api/adminapi.md'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
extra_css: [extra.css]

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'deep orange'
    accent: 'orange'
  font:
    text: 'Open Sans'
    code: 'Monaco'
